logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n

spring.ai.chat.client.enabled=false

# OpenAI API Key configuration
spring.ai.openai.api-key=${OPENAI_API_KEY}
#spring.ai.openai.api-key=dummy #required for local Llama
spring.ai.openai.chat.base-url=http://localhost:11434/v1
spring.ai.openai.image.model=gpt-image-1

#config for qdrant vector store to work
spring.autoconfigure.exclude=org.springframework.ai.model.openai.autoconfigure.OpenAiEmbeddingAutoConfiguration

#Ollama configuration
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3.1
spring.ai.model.embedding=ollama
spring.ai.ollama.embedding.options.model=bge-m3

#debug=true
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
#logging.level.org.springframework.ai=DEBUG
#logging.level.org.springframework.ai.vectorstore=DEBUG

#config for h2 database
spring.datasource.url=jdbc:h2:file:D:\\Repos\\spring-ai\\multimodel\\chatmemory;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=12345
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update

spring.ai.chat.memory.repository.jdbc.initialize-schema=always

#remove the container after stopping
spring.docker.compose.stop.command=down

#config for qdrant vector store
spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=chatmemory

#actuator config
management.endpoints.web.exposure.include=health,metrics,prometheus

#config for opentelemetry
management.opentelemetry.logging.export.otlp.endpoint=http://localhost:4318/v1/traces
management.otlp.metrics.export.enabled=false


#trace all requests
management.tracing.sampling.probability=1.0






